[build]
command = "hugo --gc --minify --cleanDestinationDir --ignoreCache"
publish = "public"  # Your final built site goes here

[build.environment]
HUGO_VERSION = "0.145.0"  # Match your local Hugo version

[context.production.environment]
HUGO_ENV = "production"